spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /iAspire
  port: 8085

logging:
  file: logs/iaspire-service.log
  level:
      org.springframework: DEBUG
      org.hibernate.SQL: DEBUG
      com.tcs.rmg: DEBUG

---
spring:
  profiles: prod
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:postgresql://10.169.38.139:5432/postgres
    #url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---
spring:
  application.name: iAspire-service
  profiles: dev
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    #url:  jdbc:postgresql://10.169.38.139:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: true
        format_sql: true
        use_sql: true
        show_sql: true


iaspire:
  digital:
    emailid:  iAspire@tcs.com
  employee:
      gradelist: BPO5,BPO6,BPO7,BPO8,BPOS,BPOZ,BPS9,C3A,C3B,C4,C5,S4,S5,SP1

eureka:
    client:
      enabled: false
      serviceUrl:
        #defaultZone: http://localhost:8761/eureka/
        #defaultZone: http://localhost:8761/eureka/
        #defaultZone: http://10.169.38.140:8761/eureka/
